apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-watcher-agent
  namespace: agents
  labels:
    app: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: data-watcher-agent
        image: watcher-agent:v1
        env:
        - name: TZ
          value: Asia/Tehran




